### ISSUE TITLE
When in Property Mode, view command does not work

### ISSUE THREAD

**Issue by KennyLewi** [AY2425S1-CS2103T-F13-2/tp#199]
https://github.com/user-attachments/assets/3b2c97c7-4a3f-4148-ab57-5bab19e38cbd

When in property mode, using the `view` command doesn't do anything, e.g after using the `find` command, using `view` doesn't re-show the full list.

To reproduce:
1. Open the ABCLI app
2. Switch to property mode using `switch p`
3. Use a `find` command, e.g. `find bishan`
4. Use `view`

**Comment by NgZiXin** [comment]
Resolved
