### ISSUE TITLE
Typo in displaying property type for successful add property command

### ISSUE THREAD

**Issue by KennyLewi** [AY2425S1-CS2103T-F13-2/tp#200]
![image](https://github.com/user-attachments/assets/d4f795b5-8cef-42bd-ba25-11ea8df13dce)

When an add property command is successfully executed, there is a typo in the success message for `Property type`.

In the image above, other fields such as "Phone: 98765432;",  "Location: Clementi;" differ from the `Property type` as it shows "Property typeHDB" (lack of colon and whitespace).

To reproduce:
1. Open ABCLI
2. Switch to property mode using `switch p`
3. Input a valid add command, e.g. `add n/John Doe p/98765432 l/Clementi a/450000 t/HDB`
4. Check the success message

**Comment by NgZiXin** [comment]
Also change format of Location -> Address
