### ISSUE TITLE
Invalid buyer index

### ISSUE THREAD

**Issue by ylchin** [AY2425S1-CS2103T-F13-2/tp#201]
<img width="1115" alt="Screenshot 2024-11-03 at 5 58 05 PM" src="https://github.com/user-attachments/assets/8cb83aaf-864f-4287-8347-66602b549760">
When index supplied is invalid, it just tells you it's invalid. Might be better to show the range of valid indexes.

**Comment by NgZiXin** [comment]
Help do for all. If it is too difficult to implement, can be further discussed
