### ISSUE TITLE
Edit and add emails allows emails with invalid top level domains to be added

### ISSUE THREAD

**Issue by ylchin** [AY2425S1-CS2103T-F13-2/tp#202]
<img width="754" alt="Screenshot 2024-11-03 at 6 39 31 PM" src="https://github.com/user-attachments/assets/66aa74a1-f945-41d1-a54a-3bba507f0146">
TLD copm is invalid and is still allowed. Perhaps before adding/editing email, verify the TLD from a known list of tlds?

**Comment by NgZiXin** [comment]
Discussed: Not a bug
