### ISSUE TITLE
Tags for buyer are not purpose-fit

### ISSUE THREAD

**Issue by ylchin** [AY2425S1-CS2103T-F13-2/tp#210]
Should be like "relocating", "reffered" etc. Also should allow dashes for tags like first-time.
<img width="863" alt="Screenshot 2024-11-04 at 1 31 21 PM" src="https://github.com/user-attachments/assets/16215e1d-0d79-4fa4-96b1-e2da1fa8ead0">

**Comment by NgZiXin** [comment]
Update the sampleDataBuyerList - Resolved
