### ISSUE TITLE
Incorrect instructions for asking price aspect of add property command

### ISSUE THREAD

**Issue by KennyLewi** [AY2425S1-CS2103T-F13-2/tp#229]
![image](https://github.com/user-attachments/assets/2b7bc8ac-797b-4ed8-a562-857ead381586)

When in property mode, the add command instruction has incorrect instructions with regards to the asking price. As seen in the picture, the inputted a/100000,000 technically "has 3 digits after the comma", but it's still marked as incorrect. While the inputted number shouldn't actually be valid, the instructions can perhaps be clearer.

To reproduce:
1. Run the ABCLI app
2. Switch to Property mode using the `switch p` command
3. Input an invalid asking price in an add command, e.g. `add n/John Doe p/98765432 l/Clementi a/100000,000 t/HDB`

**Comment by NgZiXin** [comment]
Discussed: Resolved.
