### ISSUE TITLE
Typo in displaying property type for successful edit property command

### ISSUE THREAD

**Issue by KennyLewi** [AY2425S1-CS2103T-F13-2/tp#230]
![image](https://github.com/user-attachments/assets/ff577d2c-00b3-4320-b5be-4f49a7c99061)

When an edit property command is successfully executed, there is a typo in the success message for `Property type`.

In the image above, other fields such as "Phone: 91234567;", "Location: San Francisco;" differ from the `Property type` as it shows "Property typeCondominium" (lack of colon and whitespace).

To reproduce:

1. Open ABCLI
2. Switch to property mode using `switch p`
3. Input a valid edit command, e.g. `edit 1 p/91234567 l/San Francisco a/5000000 t/Condominium`
4. Check the success message

**Comment by NgZiXin** [comment]
Resolved.
