### ISSUE TITLE
[PE-D][Tester D] Setting up link in DG is broken

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F13-2/tp#317]
![Screenshot 2024-11-08 at 7.48.10 PM.png](https://raw.githubusercontent.com/liauzhanyi/ped/main/files/2d0ea7ee-6873-4276-974d-2ab1276705ba.png)

Specifically `Setting up and getting started.`

Given the importance of setting up and even for developers, assumption cannot be made about the their tech stack knowledge hence a broken link for setting up is considered quite severe in a DG.

-------------
Labels: `type.DocumentationBug` `severity.High`
original: liauzhanyi/ped#10

**Comment by NgZiXin** [comment]
PDF conversion.
